### ISSUE TITLE
Request failed with status code 406

### ISSUE THREAD

**Issue by Jarauvi** [finnishtransportagency/infra2railml#6]
It seems that for some reason all track queries return 406, also with the default example below

root@primary:/home/tstclt/railtest# infra2railml 007 --from 28 --to 37
Loading track 007 [28..37 km] ..
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/28.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/29.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/30.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/31.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/32.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/33.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/34.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/37.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/36.json
Error: Request failed with status code 406: https://rata.digitraffic.fi/infra-api/0.3/radat/007/35.json
Error: No kilometers to process.
    at Promise (/home/tstclt/infra2railml/index.js:66:16)
    at new Promise (<anonymous>)
    at Object.createIndex (/home/tstclt/infra2railml/index.js:63:12)
    at app.getTrack.then (/home/tstclt/infra2railml/cli.js:50:26)
    at tryCatcher (/home/tstclt/infra2railml/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/home/tstclt/infra2railml/node_modules/bluebird/js/release/promise.js:643:18)

EDIT: problem occurs with also other versions of the API than 0.3

**Comment by helguts** [comment]
Same here. It has worked 2019 quite good... but not with the current version. :(

**Comment by helguts** [comment]
Hallo! 
One possible solution seems to adjust the header options. If I change "http-client.js" in \infra2railml\services as follow:
`const opts = {
    adapter: throttleAdapter,
    timeout: config.http.timeout,
	headers: {'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
		'accept-encoding': 'gzip, deflate, br',
		'accept-language': 'de,en-US;q=0.7,en;q=0.3'}
};`

I at least get rid of the 406 errors. It seems to run properly, but now generates "Error: station x.x.xxx.LIVI.INFRA.39.119094 has no position (KYT 684)" errors for the mentioned example. This results in a faulty railML file, which has then several errors in railVIVID because of some missing IDs.

Would be great to have any solution to this.

**Comment by helguts** [comment]
Ah well.. if I adjust the api version in the config from 0.3 to 0.6 it runs successfully...awesome!!!!

**Comment by jyrimatti** [comment]
Digitraffic requires compression for all requests: https://www.digitraffic.fi/ohjeita/#pakkaus
Was this the problem?

**Comment by helguts** [comment]
Ah... yes! Didnt know, that it is mentioned there. Sadly I still get alot of timeouts...:
`connect ETIMEDOUT 54.77.120.11:443: https://rata.digitraffic.fi/infra-api/0.6/elementit/1.2.246.586.1.14.132787.json`
 I think or hope that this is the reason, that railVIVID says that the generated railML files are not valid.

**Comment by jyrimatti** [comment]
I don’t know how this particular application works, but the database behind infra-api has only 2 vCpus, so concurrent requests should  probably be limited to ~2.

Also, some of the returned data is quite heavy to calculate, so if all the data is always retrieved (that is, no ”propertyName” request parameters given), the requests might spend a while in the database.

On the other hand, all the data is cached in Digitraffic frontend servers, so retrying the operations should eventually get passed the timeouts as long as too much of concurrency isn’t blocking a particular request from succeeding at all. The server has 5 minute timeout for requests.

**Comment by helguts** [comment]
Thank you very much for the insights. Sounds reasonable.

**Comment by lapintom** [comment]
Finally merged, timeouts and 406's should be fixed now. Thanks for the patches
